---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mission-control.flanksource.com
  resources:
  - connections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mission-control.flanksource.com
  resources:
  - connections/finalizers
  verbs:
  - update
- apiGroups:
  - mission-control.flanksource.com
  resources:
  - connections/status
  verbs:
  - get
  - patch
  - update
